{
  "totalNumberSkippingTests": 33,
  "bugType": "failing_passing",
  "totalNumberErroringTests": 9,
  "repo": "apache/commons-math",
  "metrics": {
    "FailureNames": [
      "org.apache.commons.math4.exception.MathArithmeticException",
      "java.lang.Exception"
    ],
    "StepsDurationsInSeconds": {
      "CheckoutBuggyBuild": 0,
      "ComputeClasspath": 4,
      "ComputeTestDir": 0,
      "ResolveDependency": 23,
      "BuildProjectBuild": 36,
      "TestProjectBuild": 191,
      "ComputeSourceDir": 0,
      "InitRepoToPush": 5,
      "BuildProjectPreviousBuild": 46,
      "GatherTestInformationBuild": 0,
      "CloneRepository": 16,
      "NopolRepair": 0,
      "CheckoutPatchedBuild": 0,
      "PushIncriminatedBuild": 7,
      "CommitPatch": 7,
      "TestProjectPreviousBuild": 185,
      "GatherTestInformationPreviousBuild": 1
    },
    "BugCommitUrl": "http://github.com/apache/commons-math/commit/50d2939125522b7fecb16546fe7a5c253566df15",
    "NbFailingTests": 9,
    "PatchCommitUrl": "http://github.com/apache/commons-math/commit/35e0ba449325e759e04203fcaa71920cf473baef",
    "ReproductionDate": "Aug 24, 2017 10:09:12 PM",
    "BuggyBuildId": 228554017,
    "PatchedBuilId": 228558805,
    "BuggyBuildURL": "http://travis-ci.org/apache/commons-math/builds/228554017",
    "PatchedBuildURL": "http://travis-ci.org/apache/commons-math/builds/228558805",
    "BuggyBuildDate": "May 4, 2017 2:03:56 AM",
    "PatchedBuildDate": "May 4, 2017 2:33:25 AM",
    "BugCommit": "50d2939125522b7fecb16546fe7a5c253566df15",
    "PatchCommit": "35e0ba449325e759e04203fcaa71920cf473baef",
    "PatchChangedFiles": 2,
    "PatchAddedLines": 0,
    "PatchDeletedLines": 0,
    "NbRunningTests": 5432,
    "NbLibraries": 11,
    "NbFileApp": 0,
    "NbFileTests": 0,
    "NbCPU": 32,
    "FreeMemory": 606112960,
    "TotalMemory": 1296564224,
    "AngelicValuesByTest": {},
    "FreeMemoryByStep": {
      "CheckoutBuggyBuild": 696938976,
      "ComputeClasspath": 388392984,
      "ComputeTestDir": 654531928,
      "ResolveDependency": 640465792,
      "BuildProjectBuild": 1130986072,
      "TestProjectBuild": 1113549480,
      "ComputeSourceDir": 664621616,
      "InitRepoToPush": 393667320,
      "BuildProjectPreviousBuild": 624639416,
      "GatherTestInformationBuild": 1056435280,
      "CloneRepository": 742523760,
      "NopolRepair": 388392984,
      "CheckoutPatchedBuild": 1175448600,
      "PushIncriminatedBuild": 709661736,
      "CommitPatch": 606112960,
      "TestProjectPreviousBuild": 606174072,
      "GatherTestInformationPreviousBuild": 544782792
    }
  },
  "bugCommit": "https://github.com/apache/commons-math/compare/e082e0c48ed6...50d293912552",
  "failingModule": "/root/workspace/apache/commons-math/228554017",
  "hostname": "spirals-vortex.lille.inria.fr",
  "totalNumberFailingTests": 0,
  "error-types": [
    "org.apache.commons.math4.exception.MathArithmeticException",
    "java.lang.Exception"
  ],
  "totalNumberRunningTests": 5432,
  "failing-test-cases": [
    {
      "className": "org.apache.commons.math4.util.CombinatoricsUtilsTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.apache.commons.math4.util.CombinatoricsUtilsTest#testFactorialFail",
        "org.apache.commons.math4.util.CombinatoricsUtilsTest#testStirlingS2Overflow"
      ],
      "failures": [
        {
          "failureName": "org.apache.commons.math4.exception.MathArithmeticException",
          "failureDetail": "arithmetic exception",
          "isError": true
        },
        {
          "failureName": "java.lang.Exception",
          "failureDetail": "Unexpected exception, expected\u003cjava.lang.ArithmeticException\u003e but was\u003corg.apache.commons.math4.exception.MathArithmeticException\u003e",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.apache.commons.math4.fraction.FractionTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.apache.commons.math4.fraction.FractionTest#testNegate",
        "org.apache.commons.math4.fraction.FractionTest#testConstructor",
        "org.apache.commons.math4.fraction.FractionTest#testSubtract",
        "org.apache.commons.math4.fraction.FractionTest#testAdd",
        "org.apache.commons.math4.fraction.FractionTest#testDivide",
        "org.apache.commons.math4.fraction.FractionTest#testGetReducedFraction",
        "org.apache.commons.math4.fraction.FractionTest#testReciprocal"
      ],
      "failures": [
        {
          "failureName": "org.apache.commons.math4.exception.MathArithmeticException",
          "failureDetail": "overflow, numerator too large after multiply: -2,147,483,649",
          "isError": true
        },
        {
          "failureName": "org.apache.commons.math4.exception.MathArithmeticException",
          "failureDetail": "overflow, numerator too large after multiply: -2,147,483,649",
          "isError": true
        },
        {
          "failureName": "org.apache.commons.math4.exception.MathArithmeticException",
          "failureDetail": "zero denominator in fraction 1/0",
          "isError": true
        },
        {
          "failureName": "org.apache.commons.math4.exception.MathArithmeticException",
          "failureDetail": "zero denominator in fraction 1/0",
          "isError": true
        },
        {
          "failureName": "org.apache.commons.math4.exception.MathArithmeticException",
          "failureDetail": "the fraction to divide by must not be zero: 0/1",
          "isError": true
        },
        {
          "failureName": "org.apache.commons.math4.exception.MathArithmeticException",
          "failureDetail": "overflow in fraction -2,147,483,648/1, cannot negate",
          "isError": true
        },
        {
          "failureName": "org.apache.commons.math4.exception.MathArithmeticException",
          "failureDetail": "overflow in fraction -2,147,483,648/-1, cannot negate",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 7
    }
  ]
}