nopolinfo #0
location: FailureLocation{className='org.example.custom.CustomAsserts_filter_stacktrace_Test', failingMethods=[org.example.custom.CustomAsserts_filter_stacktrace_Test#should_filter_when_custom_assert_fails_with_message, org.example.custom.CustomAsserts_filter_stacktrace_Test#should_filter_when_custom_assert_throws_assertion_error, org.example.custom.CustomAsserts_filter_stacktrace_Test#should_filter_when_abstract_custom_assert_fails, org.example.custom.CustomAsserts_filter_stacktrace_Test#should_filter_when_custom_assert_fails_with_overridden_message], erroringMethods=[], failures=[FailureType{failureName='java.lang.AssertionError', failureDetail='
Expecting elements:
<[org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAbstractAssert.failInAbstractAssert(CustomAsserts_filter_stacktrace_Test.java:112)]>
 of 
<[org.assertj.core.api.AbstractAssert.failWithMessage(AbstractAssert.java:112),
    org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAbstractAssert.failInAbstractAssert(CustomAsserts_filter_stacktrace_Test.java:112),
    org.example.custom.CustomAsserts_filter_stacktrace_Test.should_filter_when_abstract_custom_assert_fails(CustomAsserts_filter_stacktrace_Test.java:57),
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
    java.lang.reflect.Method.invoke(Method.java:498),
    org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50),
    org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12),
    org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47),
    org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17),
    org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26),
    org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27),
    org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325),
    org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78),
    org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57),
    org.junit.runners.ParentRunner$3.run(ParentRunner.java:290),
    org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71),
    org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288),
    org.junit.runners.ParentRunner.access$000(ParentRunner.java:58),
    org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268),
    org.junit.runners.ParentRunner.run(ParentRunner.java:363),
    org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367),
    org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274),
    org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238),
    org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161),
    org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290),
    org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242),
    org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)]>
 not to be <StackTraceElement of class org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAbstractAssert>', isError=false}, FailureType{failureName='java.lang.AssertionError', failureDetail='
Expecting elements:
<[org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAssert.fail(CustomAsserts_filter_stacktrace_Test.java:95)]>
 of 
<[org.assertj.core.api.AbstractAssert.failWithMessage(AbstractAssert.java:112),
    org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAssert.fail(CustomAsserts_filter_stacktrace_Test.java:95),
    org.example.custom.CustomAsserts_filter_stacktrace_Test.should_filter_when_custom_assert_fails_with_message(CustomAsserts_filter_stacktrace_Test.java:30),
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
    java.lang.reflect.Method.invoke(Method.java:498),
    org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50),
    org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12),
    org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47),
    org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17),
    org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26),
    org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27),
    org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325),
    org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78),
    org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57),
    org.junit.runners.ParentRunner$3.run(ParentRunner.java:290),
    org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71),
    org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288),
    org.junit.runners.ParentRunner.access$000(ParentRunner.java:58),
    org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268),
    org.junit.runners.ParentRunner.run(ParentRunner.java:363),
    org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367),
    org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274),
    org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238),
    org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161),
    org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290),
    org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242),
    org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)]>
 not to be <StackTraceElement of class org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAssert>', isError=false}, FailureType{failureName='java.lang.AssertionError', failureDetail='
Expecting elements:
<[org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAssert.throwAnAssertionError(CustomAsserts_filter_stacktrace_Test.java:100)]>
 of 
<[org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAssert.throwAnAssertionError(CustomAsserts_filter_stacktrace_Test.java:100),
    org.example.custom.CustomAsserts_filter_stacktrace_Test.should_filter_when_custom_assert_throws_assertion_error(CustomAsserts_filter_stacktrace_Test.java:48),
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
    java.lang.reflect.Method.invoke(Method.java:498),
    org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50),
    org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12),
    org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47),
    org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17),
    org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26),
    org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27),
    org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325),
    org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78),
    org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57),
    org.junit.runners.ParentRunner$3.run(ParentRunner.java:290),
    org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71),
    org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288),
    org.junit.runners.ParentRunner.access$000(ParentRunner.java:58),
    org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268),
    org.junit.runners.ParentRunner.run(ParentRunner.java:363),
    org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367),
    org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274),
    org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238),
    org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161),
    org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290),
    org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242),
    org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)]>
 not to be <StackTraceElement of class org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAssert>', isError=false}, FailureType{failureName='java.lang.AssertionError', failureDetail='
Expecting elements:
<[org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAssert.fail(CustomAsserts_filter_stacktrace_Test.java:95)]>
 of 
<[org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAssert.fail(CustomAsserts_filter_stacktrace_Test.java:95),
    org.example.custom.CustomAsserts_filter_stacktrace_Test.should_filter_when_custom_assert_fails_with_overridden_message(CustomAsserts_filter_stacktrace_Test.java:39),
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
    java.lang.reflect.Method.invoke(Method.java:498),
    org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50),
    org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12),
    org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47),
    org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17),
    org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26),
    org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27),
    org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325),
    org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78),
    org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57),
    org.junit.runners.ParentRunner$3.run(ParentRunner.java:290),
    org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71),
    org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288),
    org.junit.runners.ParentRunner.access$000(ParentRunner.java:58),
    org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268),
    org.junit.runners.ParentRunner.run(ParentRunner.java:363),
    org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367),
    org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274),
    org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238),
    org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161),
    org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290),
    org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242),
    org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)]>
 not to be <StackTraceElement of class org.example.custom.CustomAsserts_filter_stacktrace_Test$CustomAssert>', isError=false}], nbFailures=4, nbErrors=0}
status: NOPATCH
dateEnd: Tue Aug 29 13:13:13 CEST 2017
allocatedtime: 120minutes 
passingTime: 0minutes 
nb patches: 0
nopol context: Config{synthesisDepth=3, collectStaticMethods=true, collectStaticFields=false, collectLiterals=false, onlyOneSynthesisResult=false, sortExpressions=true, maxLineInvocationPerTest=250, timeoutMethodInvocation=2000, dataCollectionTimeoutInSecondForSynthesis=900, addWeight=0.19478, subWeight=0.04554, mulWeight=0.0102, divWeight=0.00613, andWeight=0.10597, orWeight=0.05708, eqWeight=0.22798, nEqWeight=0.0, lessEqWeight=0.0255, lessWeight=0.0947, methodCallWeight=0.1, fieldAccessWeight=0.08099, constantWeight=0.14232, variableWeight=0.05195, mode=REPAIR, type=COND_THEN_PRE, synthesis=DYNAMOTH, oracle=ANGELIC, solver=Z3, solverPath='./z3_for_linux', projectSources=[./workspace/joel-costigliola/assertj-core/200783543/src/main/java, /root/./workspace/joel-costigliola/assertj-core/200783543/src/main/java], projectClasspath='[Ljava.net.URL;@1b0a7baf', projectTests=[org.example.custom.CustomAsserts_filter_stacktrace_Test], complianceLevel=8, outputFolder=null, json=false}
exception: null
nbStatements: 0
nbAngelicValues: 0
ignoreStatus: NOTHING_TO_IGNORE
----------



